version: '3.8'

services:
  app:
    build:
      context: .
      target: builder
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql://user:password@db:3306/real_estate
      - JWT_SECRET=your-jwt-secret
      - GOOGLE_CLIENT_ID=your-google-client-id
      - GOOGLE_CLIENT_SECRET=your-google-client-secret
      - FACEBOOK_APP_ID=your-facebook-app-id
      - FACEBOOK_APP_SECRET=your-facebook-app-secret
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    image: mysql:8
    ports:
      - "3308:3308"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=real_estate
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
