[build]
  command = "npm run build"
  publish = ".output/public"

[build.environment]
  NODE_VERSION = "18"
  NUXT_PUBLIC_API_BASE = "https://tourmaline-lebkuchen-48d345.netlify.app/api"
  NUXT_PUBLIC_SITE_URL = "https://tourmaline-lebkuchen-48d345.netlify.app"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
