[build]
  command = "npm run build"
  publish = ".output/public"

[build.environment]
  NODE_VERSION = "18"
  NUXT_PUBLIC_API_BASE = "https://homesbyabdulojulari.netlify.app/api"
  NUXT_PUBLIC_SITE_URL = "https://homesbyabdulojulari.netlify.app"
  DATABASE_URL = "postgresql://postgres:YOUR_PASSWORD@db.dqkhgfutlnnqwbvtcauv.supabase.co:5432/postgres"
  JWT_SECRET = "your-jwt-secret-change-in-production"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
