[build]
  command = "npm run build"
  publish = ".output/public"

[functions]
  directory = ".netlify/functions-internal"

[build.environment]
  NODE_VERSION = "18"
  NUXT_PUBLIC_API_BASE = "https://homesbyabdulojulari.netlify.app/api"
  NUXT_PUBLIC_SITE_URL = "https://homesbyabdulojulari.netlify.app"
  DATABASE_URL = "${NETLIFY_DATABASE_URL}"
  JWT_SECRET = "your-jwt-secret-change-in-production"

# Let Netlify handle the functions automatically

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
