<template>
  <div>
    <!-- Hero -->
    <v-img
      height="220"
      cover
      src="https://images.unsplash.com/photo-1496307042754-b4aa456c4a2d?q=80&w=1920&auto=format&fit=crop"
      gradient="to bottom, rgba(0,0,0,.25), rgba(0,0,0,.65)"
      class="mb-6"
      referrerpolicy="no-referrer"
    >
      <div class="d-flex align-center justify-center h-100">
        <h1 class="text-h4 text-white">Privacy Policy</h1>
      </div>
    </v-img>

    <!-- Content -->
    <v-container class="py-6">
      <v-card  flat>
        <v-card-text class="py-6 px-6 px-md-10">
          <div class="text-center mb-6">
            <NuxtLink to="/" class="text-primary text-decoration-none font-weight-medium">← Back to home</NuxtLink>
            <div class="text-body-2 text-medium-emphasis mt-2">Last updated: September 3, 2025</div>
          </div>

          <section class="mb-6">
            <p class="mb-3">This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
            <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>
          </section>

          <section class="mb-6">
            <h2 class="text-h6 mb-3">Interpretation and Definitions</h2>
            <h3 class="text-subtitle-1 mb-2">Interpretation</h3>
            <p class="mb-4">The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>

            <h3 class="text-subtitle-1 mb-2">Definitions</h3>
            <v-sheet color="#f9f9f9" rounded class="pa-4">
              <div class="mb-2"><strong class="text-primary">Account</strong> means a unique account created for You to access our Service or parts of our Service.</div>
              <div class="mb-2"><strong class="text-primary">Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</div>
              <div class="mb-2"><strong class="text-primary">Application</strong> refers to PropertyMatch, the software program provided by the Company.</div>
              <div class="mb-2"><strong class="text-primary">Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to PropertyMatch.</div>
              <div class="mb-2"><strong class="text-primary">Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</div>
              <div class="mb-2"><strong class="text-primary">Country</strong> refers to: Alberta, Canada</div>
              <div class="mb-2"><strong class="text-primary">Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</div>
              <div class="mb-2"><strong class="text-primary">Personal Data</strong> is any information that relates to an identified or identifiable individual.</div>
              <div class="mb-2"><strong class="text-primary">Service</strong> refers to the Application or the Website or both.</div>
              <div class="mb-2"><strong class="text-primary">Third-party Social Media Service</strong> refers to any website or any social network website through which a User can log in or create an account to use the Service.</div>
              <div class="mb-2"><strong class="text-primary">Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</div>
              <div class="mb-2"><strong class="text-primary">Website</strong> refers to PropertyMatch, accessible from <a href="https://www.propertymatch.estate" target="_blank" rel="noopener" class="text-primary">https://www.propertymatch.estate</a></div>
              <div><strong class="text-primary">You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</div>
            </v-sheet>
          </section>

          <section class="mb-6">
            <h2 class="text-h6 mb-3">Collecting and Using Your Personal Data</h2>
            <h3 class="text-subtitle-1 mb-2">Types of Data Collected</h3>

            <h4 class="text-subtitle-2 mb-2">Personal Data</h4>
            <p class="mb-2">While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
            <ul class="pl-6 mb-4">
              <li>Email address</li>
              <li>First name and last name</li>
              <li>Phone number</li>
              <li>Address, State, Province, ZIP/Postal code, City</li>
              <li>Usage Data</li>
            </ul>

            <h4 class="text-subtitle-2 mb-2">Usage Data</h4>
            <p class="mb-2">Usage Data is collected automatically when using the Service.</p>
            <p class="mb-4">Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data. When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>

            <h4 class="text-subtitle-2 mb-2">Information from Third-Party Social Media Services</h4>
            <p class="mb-2">The Company allows You to create an account and log in to use the Service through the following Third-party Social Media Services:</p>
            <ul class="pl-6 mb-4">
              <li>Google</li>
              <li>Facebook</li>
              <li>Instagram</li>
              <li>Twitter</li>
              <li>LinkedIn</li>
            </ul>

            <h4 class="text-subtitle-2 mb-2">Information Collected while Using the Application</h4>
            <p class="mb-2">While using Our Application, in order to provide features of Our Application, We may collect, with Your prior permission:</p>
            <ul class="pl-6 mb-4">
              <li>Information regarding your location</li>
              <li>Information from your Device's phone book (contacts list)</li>
              <li>Pictures and other information from your Device's camera and photo library</li>
            </ul>

            <h4 class="text-subtitle-2 mb-2">Tracking Technologies and Cookies</h4>
            <p class="mb-2">We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. The technologies We use may include:</p>
            <ul class="pl-6">
              <li><strong>Cookies or Browser Cookies:</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent.</li>
              <li><strong>Web Beacons:</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons.</li>
            </ul>
          </section>

          <section class="mb-6">
            <h2 class="text-h6 mb-3">Use of Your Personal Data</h2>
            <p class="mb-2">The Company may use Personal Data for the following purposes:</p>
            <ul class="pl-6">
              <li><strong>To provide and maintain our Service,</strong> including to monitor the usage of our Service.</li>
              <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service.</li>
              <li><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased.</li>
              <li><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.</li>
              <li><strong>To provide You</strong> with news, special offers and general information about other goods, services and events.</li>
              <li><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</li>
              <li><strong>For business transfers:</strong> We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets.</li>
            </ul>
          </section>

          <section class="mb-6">
            <h2 class="text-h6 mb-3">Retention of Your Personal Data</h2>
            <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.</p>
          </section>

          <section class="mb-6">
            <h2 class="text-h6 mb-3">Transfer of Your Personal Data</h2>
            <p>Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>
          </section>

          <section class="mb-6">
            <h2 class="text-h6 mb-3">Delete Your Personal Data</h2>
            <p>You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You. Our Service may give You the ability to delete certain information about You from within the Service.</p>
          </section>

          <section class="mb-6">
            <h2 class="text-h6 mb-3">Disclosure of Your Personal Data</h2>
            <h4 class="text-subtitle-2 mb-2">Business Transactions</h4>
            <p class="mb-3">If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>
            <h4 class="text-subtitle-2 mb-2">Law Enforcement</h4>
            <p>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities.</p>
          </section>

          <section class="mb-6">
            <h2 class="text-h6 mb-3">Security of Your Personal Data</h2>
            <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
          </section>

          <section class="mb-6">
            <h2 class="text-h6 mb-3">Children's Privacy</h2>
            <p>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us.</p>
          </section>

          <section class="mb-6">
            <h2 class="text-h6 mb-3">Links to Other Websites</h2>
            <p>Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.</p>
          </section>

          <section class="mb-6">
            <h2 class="text-h6 mb-3">Changes to this Privacy Policy</h2>
            <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page and update the "Last updated" date at the top of this Privacy Policy.</p>
          </section>

          <v-sheet color="#f8f9fa" rounded class="pa-4">
            <h2 class="text-h6 mb-2">Contact Us</h2>
            <p class="mb-2">If you have any questions about this Privacy Policy, You can contact us:</p>
            <ul class="pl-6">
              <li>By email: abdul.ojulari@exprealty.com</li>
              <li>By visiting this page on our website: <a href="https://www.propertymatch.estate" target="_blank" rel="noopener" class="text-primary">https://www.propertymatch.estate</a></li>
              <li>By phone number: 6478037236</li>
            </ul>
          </v-sheet>
        </v-card-text>
      </v-card>

    
    </v-container>
  </div>
</template>

<script setup lang="ts">
definePageMeta({ layout: 'default' })
</script>
